//! corrald-ui binary: tokio runtime + eframe (wgpu renderer).

use eframe::egui;

/// The window/app icon, embedded at compile time from the rendered master
/// (assets/icon/corral-icon-256.png — generated by
/// tools/icon/from-user-png.py from the approved source PNG).
fn app_icon() -> egui::IconData {
    let bytes = include_bytes!("../../../assets/icon/corral-icon-256.png");
    let img = image::load_from_memory(bytes).expect("embedded icon PNG is valid");
    let rgba = img.to_rgba8();
    let (width, height) = (rgba.width(), rgba.height());
    egui::IconData {
        rgba: rgba.into_raw(),
        width,
        height,
    }
}

fn viewport_builder() -> egui::ViewportBuilder {
    egui::ViewportBuilder::default()
        .with_inner_size([1320.0, 860.0])
        .with_min_inner_size([900.0, 600.0])
        .with_title("corral fleet")
        .with_icon(app_icon())
}

fn main() -> eframe::Result {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("tokio runtime");

    let options = eframe::NativeOptions {
        viewport: viewport_builder(),
        renderer: eframe::Renderer::Wgpu,
        ..Default::default()
    };

    eframe::run_native(
        "corral fleet",
        options,
        Box::new(|cc| {
            Ok(Box::new(corrald_ui::app::CorralApp::new(
                cc,
                rt.handle().clone(),
            )))
        }),
    )
}

#[cfg(test)]
mod tests {
    use super::viewport_builder;

    #[test]
    fn viewport_builder_applies_embedded_icon() {
        let viewport = viewport_builder();
        let icon = viewport.icon.expect("viewport icon");
        assert_eq!((icon.width, icon.height), (256, 256));
        assert_eq!(
            icon.rgba.len(),
            icon.width as usize * icon.height as usize * 4
        );
        assert!(icon.rgba.iter().any(|pixel| *pixel != 0));
    }
}
